from tkinter import *
from tkinter import messagebox  
def Startgame():
        Photostart=PhotoImage(file='dg.png') #ภาพพื้นหลัง
        canvas.create_image(0,800,anchor=SW,image=Photostart)
        backbutton=PhotoImage(file='back.png')
        global back
        back=Button(tk,image=backbutton,borderwidth=0,command=Trunback,bg='green')#ปุ่มย้อนกลับ
        back.place(x=900,y=20)
        start.destroy() #ลบปุ่ม
        exit1.destroy()
        Photonumber1=PhotoImage(file='go.png') 
        canvas.create_image(150,700,anchor=SW,image=Photonumber1)
        Photonumber2=PhotoImage(file='1.png') 
        canvas.create_image(250,700,anchor=SW,image=Photonumber2)
        Photonumber3=PhotoImage(file='2.png') 
        canvas.create_image(350,700,anchor=SW,image=Photonumber3)
        Photonumber4=PhotoImage(file='3.png') 
        canvas.create_image(450,700,anchor=SW,image=Photonumber4)
        Photonumber5=PhotoImage(file='4.png') 
        canvas.create_image(550,700,anchor=SW,image=Photonumber5)
        Photonumber6=PhotoImage(file='5.png') 
        canvas.create_image(650,700,anchor=SW,image=Photonumber6)
        Photonumber7=PhotoImage(file='6.png') 
        canvas.create_image(750,700,anchor=SW,image=Photonumber7)
        Photonumber8=PhotoImage(file='13.png') 
        canvas.create_image(150,600,anchor=SW,image=Photonumber8)
        Photonumber9=PhotoImage(file='12.png') 
        canvas.create_image(250,600,anchor=SW,image=Photonumber9)
        Photonumber10=PhotoImage(file='11.png') 
        canvas.create_image(350,600,anchor=SW,image=Photonumber10)
        Photonumber11=PhotoImage(file='10.png') 
        canvas.create_image(450,600,anchor=SW,image=Photonumber11)
        Photonumber12=PhotoImage(file='9.png') 
        canvas.create_image(550,600,anchor=SW,image=Photonumber12)
        Photonumber13=PhotoImage(file='8.png') 
        canvas.create_image(650,600,anchor=SW,image=Photonumber13)
        Photonumber14=PhotoImage(file='7.png') 
        canvas.create_image(750,600,anchor=SW,image=Photonumber14)
        Photonumber15=PhotoImage(file='14.png') 
        canvas.create_image(150,500,anchor=SW,image=Photonumber15)
        Photonumber16=PhotoImage(file='15.png') 
        canvas.create_image(250,500,anchor=SW,image=Photonumber16)
        Photonumber17=PhotoImage(file='16.png') 
        canvas.create_image(350,500,anchor=SW,image=Photonumber17)
        Photonumber18=PhotoImage(file='17.png') 
        canvas.create_image(450,500,anchor=SW,image=Photonumber18)
        Photonumber19=PhotoImage(file='18.png') 
        canvas.create_image(550,500,anchor=SW,image=Photonumber19)
        Photonumber20=PhotoImage(file='19.png') 
        canvas.create_image(650,500,anchor=SW,image=Photonumber20)
        Photonumber21=PhotoImage(file='20.png') 
        canvas.create_image(750,500,anchor=SW,image=Photonumber21)
        Photonumber22=PhotoImage(file='21.png') 
        canvas.create_image(150,400,anchor=SW,image=Photonumber22)
        Photonumber23=PhotoImage(file='27.png') 
        canvas.create_image(250,400,anchor=SW,image=Photonumber23)
        Photonumber24=PhotoImage(file='26.png') 
        canvas.create_image(350,400,anchor=SW,image=Photonumber24)
        Photonumber25=PhotoImage(file='25.png') 
        canvas.create_image(450,400,anchor=SW,image=Photonumber25)
        Photonumber26=PhotoImage(file='24.png') 
        canvas.create_image(550,400,anchor=SW,image=Photonumber26)
        Photonumber27=PhotoImage(file='23.png') 
        canvas.create_image(650,400,anchor=SW,image=Photonumber27)
        Photonumber28=PhotoImage(file='22.png') 
        canvas.create_image(750,400,anchor=SW,image=Photonumber28)
        tk.mainloop() 
def Trunback():
        e=messagebox.askyesno(title='คำยืนยัน',message='คุณต้องการย้อนกลับหรือไม่')
        if e>0:
            back.destroy()
            snack_id=PhotoImage(file='b1.png')
            canvas.create_image(0,800,anchor=SW,image=snack_id)
            Photo1=PhotoImage(file='start3.png')
            start=Button(tk,image=Photo1,command=Startgame,borderwidth=5)
            start.place(x=150,y=225)
            Photo2=PhotoImage(file='exit2.png')
            exit1=Button(tk,image=Photo2,command=aexit,borderwidth=5)
            exit1.place(x=700,y=225)
            canvas.pack()
            tk.mainloop()
            
def aexit():
        d=messagebox.askyesno(title='คำยืนยัน',message='คุณต้องการออกจากเกมส์หรือไม่')
        if d>0:
            tk.destroy()
 

tk=Tk()
canvas=Canvas(tk,width=1000,height=800)
canvas.create_rectangle(0,0,1000,1000,fill='pink')
snack_id=PhotoImage(file='b1.png')
canvas.create_image(0,800,anchor=SW,image=snack_id)
Photo1=PhotoImage(file='start3.png')
start=Button(tk,image=Photo1,command=Startgame,borderwidth=5)
start.place(x=150,y=225)
Photo2=PhotoImage(file='exit2.png')
exit1=Button(tk,image=Photo2,command=aexit,borderwidth=5)
exit1.place(x=700,y=225)
canvas.pack()
tk.mainloop()