from tkinter import *
tk=Tk()
canvas=Canvas(tk,width=1000,height=800)
canvas.create_rectangle(0,0,1000,1000,fill='pink')
snack_id=PhotoImage(file='b1.png')
canvas.create_image(0,800,anchor=SW,image=snack_id)
Photo1=PhotoImage(file='start3.png')
start=Button(tk,image=Photo1,command=Startgame(),borderwidth=5)
start.place(x=150,y=225)
Photo2=PhotoImage(file='exit2.png')
exit1=Button(tk,image=Photo2,command=aexit(),borderwidth=5)
exit1.place(x=700,y=225)
canvas.pack()        
tk.mainloop()
